#!/usr/bin/env bash

set -euo pipefail

cd "{{ .ProjectSnake }}"

fd -H -tf --exec-batch chmod -x

mise trust
mise run pinact --update

for pkg in packages/*/; do
  [[ -d "$pkg" ]] || continue
  (cd "$pkg" && gleam deps download)
done

git init
git add .
