name = "{{ .ProjectSnake }}"
version = "1.0.0"
description = "{{ .Scaffold.description }}"
licences = [
  {{ if .Computed.hasApache }}"Apache-2.0",{{ end }}
  {{ if .Computed.hasMit }}"MIT",{{ end }}
]
gleam = ">= {{ .Computed.gleamMinVersion }}"

[repository]
type = "github"
user = "{{ .Scaffold.githubOwner }}"
repo = "{{ .ProjectSnake }}"
path = "{{ .ProjectSnake }}"

[[links]]
title = "Licence"
href = "{{.Computed.githubUrl}}/blob/main/LICENCE.md"

[[links]]
title = "Security"
href = "{{.Computed.githubUrl}}/blob/main/SECURITY.md"

[[links]]
title = "Code of Conduct"
href = "{{.Computed.githubUrl}}/blob/main/CODE_OF_CONDUCT.md"

[[links]]
title = "Contributing"
href = "{{.Computed.githubUrl}}/blob/main/CONTRIBUTING.md"

[[links]]
title = "Sponsor"
href = "https://github.com/sponsors/{{.Scaffold.githubOwner}}"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glinter = ">= 2.15.0 and < 3.0.0"

[tools.glinter]
stats = true

[tools.glinter.rules]
ffi_usage = "warning"
function_complexity = "warning"
module_complexity = "warning"

[javascript.deno]
allow_read = ["gleam.toml", "test"]
